/**
 * React Example: Bar Plot with Raw SVG String
 *
 * This example shows how to use MaidrChart with an existing SVG string,
 * which is useful when you have SVG content from a file, API, or
 * generated by a charting library.
 */

import type { Maidr } from '../../src/type/grammar';
import { TraceType } from '../../src/type/grammar';
import { MaidrChart } from '../../src/ui/MaidrChart';
import React from 'react';

// The MAIDR data structure describing the chart
const barData: Maidr = {
  id: 'bar',
  title: 'The Number of Tips by Day',
  subplots: [[{
    layers: [{
      id: '0',
      type: TraceType.BAR,
      selectors: 'path[clip-path="url(#p0f12ed050e)"]',
      axes: { x: 'Day', y: 'Count' },
      data: [
        { x: 'Sat', y: 87 },
        { x: 'Sun', y: 76 },
        { x: 'Thur', y: 62 },
        { x: 'Fri', y: 19 },
      ],
    }],
  }]],
};

// Raw SVG string - this could come from a file, API, or charting library
const svgString = `<svg
  id="bar"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  width="720pt"
  height="432pt"
  viewBox="0 0 720 432"
  xmlns="http://www.w3.org/2000/svg"
  version="1.1"
  tabindex="0"
>
  <defs>
    <style type="text/css">
      * {
        stroke-linejoin: round;
        stroke-linecap: butt;
      }
    </style>
  </defs>
  <g id="figure_1">
    <g id="patch_1">
      <path
        d="M 0 432 L 720 432 L 720 0 L 0 0 z"
        style="fill: #ffffff"
      />
    </g>
    <g id="axes_1">
      <g id="patch_2">
        <path
          d="M 90 384.48 L 648 384.48 L 648 51.84 L 90 51.84 z"
          style="fill: #ffffff"
        />
      </g>
      <g id="patch_3">
        <path
          d="M 115.363636 384.48 L 222.157895 384.48 L 222.157895 67.68 L 115.363636 67.68 z"
          clip-path="url(#p0f12ed050e)"
          style="fill: #87ceeb"
        />
      </g>
      <g id="patch_4">
        <path
          d="M 248.856459 384.48 L 355.650718 384.48 L 355.650718 107.735172 L 248.856459 107.735172 z"
          clip-path="url(#p0f12ed050e)"
          style="fill: #87ceeb"
        />
      </g>
      <g id="patch_5">
        <path
          d="M 382.349282 384.48 L 489.143541 384.48 L 489.143541 158.714483 L 382.349282 158.714483 z"
          clip-path="url(#p0f12ed050e)"
          style="fill: #87ceeb"
        />
      </g>
      <g id="patch_6">
        <path
          d="M 515.842105 384.48 L 622.636364 384.48 L 622.636364 315.293793 L 515.842105 315.293793 z"
          clip-path="url(#p0f12ed050e)"
          style="fill: #87ceeb"
        />
      </g>
      <g id="patch_7">
        <path
          d="M 90 384.48 L 90 51.84"
          style="fill: none; stroke: #000000; stroke-width: 0.8; stroke-linejoin: miter; stroke-linecap: square"
        />
      </g>
      <g id="patch_8">
        <path
          d="M 648 384.48 L 648 51.84"
          style="fill: none; stroke: #000000; stroke-width: 0.8; stroke-linejoin: miter; stroke-linecap: square"
        />
      </g>
      <g id="patch_9">
        <path
          d="M 90 384.48 L 648 384.48"
          style="fill: none; stroke: #000000; stroke-width: 0.8; stroke-linejoin: miter; stroke-linecap: square"
        />
      </g>
      <g id="patch_10">
        <path
          d="M 90 51.84 L 648 51.84"
          style="fill: none; stroke: #000000; stroke-width: 0.8; stroke-linejoin: miter; stroke-linecap: square"
        />
      </g>
    </g>
  </g>
  <defs>
    <clipPath id="p0f12ed050e">
      <rect x="90" y="51.84" width="558" height="332.64" />
    </clipPath>
  </defs>
</svg>`;

/**
 * BarPlotWithRawSvg Component
 *
 * Demonstrates using MaidrChart with a raw SVG string via dangerouslySetInnerHTML.
 * This approach is useful when:
 * - You have SVG content from an API or file
 * - You're migrating from the script-tag approach
 * - Your SVG is generated by another library
 */
const BarPlotWithRawSvg: React.FC = () => {
  return (
    <div style={{ padding: '20px' }}>
      <h1>Bar Plot Example with Raw SVG</h1>
      <p>
        Click on the chart or tab to it, then use arrow keys to navigate.
        Press H for help.
      </p>

      <MaidrChart maidrData={barData}>
        {/* eslint-disable-next-line react/no-danger */}
        <div dangerouslySetInnerHTML={{ __html: svgString }} />
      </MaidrChart>
    </div>
  );
};

export default BarPlotWithRawSvg;
