name: Check Examples Directory

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-examples:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to add comments to PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper diff

      - name: Check for changes in examples/
        id: check-examples
        run: |
          if git diff --name-only origin/main | grep '^examples/'; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            echo "Changes detected in examples/"
            exit 0  # Don't fail the workflow, we'll handle it with a comment
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            echo "No changes in examples/"
          fi

      - name: Add comment for e2e tests
        if: steps.check-examples.outputs.changes_detected == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const prNumber = context.issue.number;

            const comment = [
              '⚠️ **Changes detected in examples directory**',
              '',
              'This PR contains changes to files in the `examples/` directory. Before merging, please ensure:',
              '',
              '1. Run the e2e tests locally:',
              '   ```bash',
              '   npm run e2e',
              '   ```',
              '',
              '2. Verify that all examples still work as expected',
              '3. Update any relevant documentation if needed',
              '',
              `If you need help running the tests, please refer to our [testing documentation](https://github.com/${owner}/${repo}/blob/main/E2E_TESTING.md).`
            ].join('\n');

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: comment
            });
