name: Validate Changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to add comments to PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper diff

      - name: Check for changes in examples/
        id: check-examples
        run: |
          if git diff --name-only origin/main | grep -E '^(examples/|src/ui/)'; then
            echo "examples_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in examples/ or src/ui/"
          else
            echo "examples_changes=false" >> $GITHUB_OUTPUT
            echo "No changes in examples/ or src/ui/"
          fi

      - name: Check for changes in model-related files
        id: check-model
        run: |
          if git diff --name-only origin/main | grep -E '^src/(model|type|service|ui|util)/'; then
            echo "model_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in model-related files"
          else
            echo "model_changes=false" >> $GITHUB_OUTPUT
            echo "No changes in model-related files"
          fi

      - name: Add comment for examples changes
        if: steps.check-examples.outputs.examples_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const prNumber = context.issue.number;

            const comment = [
              '⚠️ **Changes detected in examples or UI directory**',
              '',
              'This PR contains changes to files in the `examples/` or `src/ui/` directories. Before merging, please ensure:',
              '',
              '1. Run the e2e tests locally:',
              '   ```bash',
              '   npm run e2e',
              '   ```',
              '',
              '2. Verify that all examples still work as expected',
              '3. Update any relevant documentation if needed',
              '',
              `If you need help running the tests, please refer to our [testing documentation](https://github.com/${owner}/${repo}/blob/main/E2E_TESTING.md).`
            ].join('\n');

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: comment
            });

      - name: Add comment for model changes
        if: steps.check-model.outputs.model_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const prNumber = context.issue.number;

            const comment = [
              '⚠️ **Changes detected in object structure files**',
              '',
              'This PR contains changes to files that affect the model layer and unit tests. Before merging, please ensure:',
              '',
              '1. Run the unit tests locally:',
              '   ```bash',
              '   npm run test',
              '   ```',
              '',
              '2. Update tests if necessary'
            ].join('\n');

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: comment
            });
